package com.test.automation.sdk.evidence;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.devtools.HasDevTools;

import com.test.automation.sdk.config.ConfigurationManager;
import com.test.automation.sdk.evidence.network.CdpNetworkAdapter;
import com.test.automation.sdk.evidence.network.CdpNetworkAdapters;
import com.test.automation.sdk.evidence.network.CdpNetworkSession;

/**
 * SDK v1.5.1 -- optional browser network trace evidence for Web failures.
 *
 * <p><b>Terminology:</b> the artifact produced by this class is a
 * <em>browser network trace</em> -- a simplified, best-effort JSON record of
 * observed request/response metadata. It is <b>not</b> a canonical HAR (HTTP
 * Archive) document and is not validated against the HAR 1.2 specification
 * (it omits per-phase timings, exact body sizes, and other required HAR
 * fields). It is intentionally never called "HAR" anywhere in this SDK's
 * public API, artifact names, or documentation.
 *
 * <h3>CDP isolation</h3>
 * This orchestrator has no dependency on any specific Chrome DevTools
 * Protocol version. All CDP-version-specific code lives behind the
 * {@link CdpNetworkAdapter} / {@link CdpNetworkSession} seam in
 * {@code com.test.automation.sdk.evidence.network} (currently a single
 * {@code v146}-based adapter). Replacing the pinned CDP version in a future
 * release only requires a new adapter implementation registered in
 * {@link CdpNetworkAdapters} -- this class does not need to change.
 *
 * <h3>Actual browser support</h3>
 * <ul>
 *   <li><b>Chrome / Edge (Chromium-based)</b> -- supported via CDP, subject
 *       to the currently registered adapter(s) accepting the runtime-detected
 *       browser/version (see {@link CdpNetworkAdapter#supports(WebDriver)}).</li>
 *   <li><b>Firefox</b> -- NOT supported. {@code FirefoxDriver} does not
 *       implement {@link HasDevTools} in this SDK's pinned Selenium version.
 *       {@link #attachIfEnabled} is a safe no-op for Firefox.</li>
 * </ul>
 * When no registered adapter can attach (unsupported browser, or a detected
 * CDP-version incompatibility), a WARN/DEBUG message explains why and
 * capture is skipped -- network evidence capture must never fail the test.
 *
 * <h3>Lifecycle</h3>
 * Network evidence useful for a failure is generated by actions that
 * happened <em>before</em> the failure, so this recorder attaches a
 * lightweight CDP listener at driver-creation time (see
 * {@code WebDriverFactory}) and buffers a bounded, in-memory list of
 * request/response pairs for the life of the session. The buffered trace is
 * only serialized to disk when {@link #detachAndWrite(WebDriver, File, String)}
 * is called -- normally only on test failure -- so passing tests never pay
 * artifact-generation cost. When network capture is disabled (the default),
 * no CDP session is created at all and there is no measurable overhead.
 *
 * <h3>Redaction</h3>
 * When {@code evidence.network.redactSensitiveData} is {@code true} (default),
 * sensitive header/parameter values (e.g. {@code Authorization}, {@code Cookie},
 * {@code Set-Cookie}, common API-key/token header names) are masked by the
 * adapter <em>before an entry is ever buffered</em> -- not only at
 * report-attachment time -- so the in-memory trace never holds the raw
 * sensitive value in the first place. Redaction is name-based (see
 * {@code SecretRedactor}); request/response <em>body</em> content is not
 * currently captured at all (only method/URL/headers/status/mimeType), so
 * there is nothing in the body to redact -- this is documented as a known
 * limitation of the simplified artifact format, not a redaction gap.
 */
public final class NetworkTraceRecorder {

    private static final Logger log = LogManager.getLogger(NetworkTraceRecorder.class);
    private static final DateTimeFormatter FILE_STAMP =
            DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss-SSS").withZone(ZoneOffset.UTC);

    /** Keyed by the driver instance handed to test code (weak so sessions are GC-able once the test ends). */
    private static final Map<WebDriver, CdpNetworkSession> ACTIVE =
            Collections.synchronizedMap(new WeakHashMap<WebDriver, CdpNetworkSession>());

    private NetworkTraceRecorder() {
    }

    /**
     * Starts buffering network traffic for {@code driver} when
     * {@code evidence.network.enabled=true} and a registered adapter supports
     * this driver. Fail-safe: any failure (unsupported browser, CDP-version
     * incompatibility, DevTools session error) is logged and skipped -- it
     * never fails driver creation or the test.
     *
     * @param driver the WebDriver session to observe (raw, pre-{@code EventFiringDecorator} instance recommended)
     */
    public static void attachIfEnabled(WebDriver driver) {
        try {
            if (!ConfigurationManager.getEvidenceConfig().networkEnabled()) {
                return;
            }
            CdpNetworkAdapter adapter = resolveAdapter(driver);
            if (adapter == null) {
                log.warn("[NetworkTraceRecorder] evidence.network.enabled=true but no registered CDP network "
                        + "adapter supports this driver/browser (only Chrome/Edge are supported, and the CDP "
                        + "version must be compatible) -- network trace capture unavailable for this session");
                return;
            }
            boolean redact = ConfigurationManager.getEvidenceConfig().networkRedactSensitiveData();
            int maxEntries = ConfigurationManager.getEvidenceConfig().networkMaxEntries();
            CdpNetworkSession session = adapter.attach(driver, maxEntries, redact);
            ACTIVE.put(driver, session);
        } catch (Exception e) {
            log.warn("[NetworkTraceRecorder] Failed to start network trace capture -- continuing without it: {}", e.getMessage());
        }
    }

    private static CdpNetworkAdapter resolveAdapter(WebDriver driver) {
        for (CdpNetworkAdapter adapter : CdpNetworkAdapters.all()) {
            try {
                if (adapter.supports(driver)) {
                    return adapter;
                }
            } catch (Exception e) {
                log.debug("[NetworkTraceRecorder] adapter '{}' detection failed: {}", adapter.name(), e.getMessage());
            }
        }
        return null;
    }

    /**
     * Stops capturing and, if any entries were buffered, writes the trace to a
     * network-trace JSON file under {@code outputDir}. Returns {@code null}
     * (never throws) when capture was never started, nothing was captured, or
     * the write fails.
     */
    public static Path detachAndWrite(WebDriver driver, File outputDir, String namePrefix) {
        CdpNetworkSession session = ACTIVE.remove(driver);
        if (session == null) {
            return null;
        }
        try {
            return writeTrace(session, outputDir, namePrefix);
        } catch (Exception e) {
            log.warn("[NetworkTraceRecorder] Failed to write network trace: {}", e.getMessage());
            return null;
        } finally {
            session.close();
        }
    }

    /** Detaches and discards any active session for {@code driver} without writing a trace (e.g. on passing tests). */
    public static void detachQuietly(WebDriver driver) {
        CdpNetworkSession session = ACTIVE.remove(driver);
        if (session != null) {
            session.close();
        }
    }

    private static Path writeTrace(CdpNetworkSession session, File outputDir, String namePrefix) throws IOException {
        List<JSONObject> entries = session.snapshotEntries();
        if (entries.isEmpty()) {
            return null;
        }

        JSONArray entriesJson = new JSONArray();
        for (JSONObject entry : entries) {
            entriesJson.put(entry);
        }

        JSONObject trace = new JSONObject();
        trace.put("format", "sdk-network-trace-v1");
        trace.put("generatedBy", "cross-platform-functional-test-automation-sdk");
        trace.put("sdkVersion", "1.5.1");
        trace.put("note", "Simplified browser network trace -- not a canonical HAR document");
        trace.put("entries", entriesJson);

        Files.createDirectories(outputDir.toPath());
        String safeName = namePrefix.replaceAll("[^a-zA-Z0-9_-]", "_");
        Path file = outputDir.toPath().resolve(safeName + "_" + FILE_STAMP.format(Instant.now()) + "_network-trace.json");
        Files.write(file, trace.toString(2).getBytes(StandardCharsets.UTF_8));
        return file;
    }
}
