package com.test.automation.sdk.tools.pageobject;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.test.automation.sdk.mobile.config.MobileConfigReader;
import com.test.automation.sdk.tools.crawler.mobile.MobileElementInfo;
import com.test.automation.sdk.tools.crawler.mobile.MobileLocatorCandidate;
import com.test.automation.sdk.tools.crawler.mobile.MobileScreenSnapshot;

/**
 * <p><b>Unified SDK Review Priority 3</b> ({@code docs/proposals/Unified_SDK_Implementation_Review_Findings_2026-09-09.md}, section 9): this implementation was moved into the formal {@code tools.*} structure as a package reorganization only; the underlying crawler/generator logic was intentionally preserved.
 * Emits a ready-to-edit {@code @AndroidFindBy}/{@code @iOSXCUITFindBy} page object
 * from a {@link MobileScreenSnapshot}'s analyzed elements -- mobile analogue of the
 * desktop SDK's {@code PageObjectGenerator}.
 *
 * Only elements with a resolved {@code UNIQUE [x]} candidate get a real {@code @FindBy}
 * field; unresolved elements are emitted as a commented-out block instead of a broken
 * field, mirroring the desktop generator's "skip unresolvable elements" convention.
 */
public final class MobilePageObjectGenerator {

    private static final Logger log = LogManager.getLogger(MobilePageObjectGenerator.class.getName());

    private MobilePageObjectGenerator() {}

    /** Resolution order: {@code -Dpog.mobile.package} &gt; {@code mobile-config.yaml crawler.pageObject.package} &gt; default. */
    public static String resolvePackage() {
        String v = System.getProperty("pog.mobile.package");
        if (v != null && !v.isEmpty()) {
            return v;
        }
        return MobileConfigReader.get("crawler.pageObject.package", "com.mycompany.automation.uiActions");
    }

    /** Resolution order: {@code -Dpog.mobile.outputDir} &gt; {@code mobile-config.yaml crawler.pageObject.outputDir} &gt; default. */
    public static String resolveOutputDir() {
        String v = System.getProperty("pog.mobile.outputDir");
        if (v != null && !v.isEmpty()) {
            return v;
        }
        return MobileConfigReader.get("crawler.pageObject.outputDir",
                "src/main/java/com/test/automation/sdk/mobile/uiActions/");
    }

    /** Renders the page object source as a string (unit-testable, no filesystem access). */
    public static String generate(String className, MobileScreenSnapshot snapshot) {
        className = JavaIdentifier.requireTypeName(className, "className");
        String packageName = resolvePackage();
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(packageName).append(";\n\n");
        sb.append("import org.apache.logging.log4j.LogManager;\n");
        sb.append("import org.apache.logging.log4j.Logger;\n");
        sb.append("import org.openqa.selenium.WebElement;\n");
        sb.append("import org.openqa.selenium.support.CacheLookup;\n");
        sb.append("import org.openqa.selenium.support.PageFactory;\n\n");
        sb.append("import io.appium.java_client.AppiumDriver;\n");
        sb.append("import io.appium.java_client.pagefactory.AndroidFindBy;\n");
        sb.append("import io.appium.java_client.pagefactory.AppiumFieldDecorator;\n");
        sb.append("import io.appium.java_client.pagefactory.iOSXCUITFindBy;\n\n");
        sb.append("import com.test.automation.sdk.mobile.testbase.MobileTestBase;\n\n");
        sb.append("/**\n * Generated by MobilePageObjectGenerator -- review and keep only UNIQUE [x] locators.\n")
                .append(" * Platform at crawl time: ").append(snapshot.getPlatform()).append("\n */\n");
        sb.append("public class ").append(className).append(" extends MobileTestBase {\n\n");
        sb.append("    public static final Logger log =\n")
                .append("            LogManager.getLogger(").append(className).append(".class.getName());\n\n");
        sb.append("    public ").append(className).append("(AppiumDriver driver) {\n");
        sb.append("        this.driver = driver;\n");
        sb.append("        PageFactory.initElements(new AppiumFieldDecorator(driver), this);\n");
        sb.append("    }\n\n");

        int unresolvedCount = 0;
        Map<String, Integer> fieldCounts = new LinkedHashMap<>();
        for (MobileElementInfo info : snapshot.getNativeElements()) {
            MobileLocatorCandidate best = info.getBestUniqueCandidate();
            if (best == null) {
                unresolvedCount++;
                sb.append("    // UNRESOLVED -- no UNIQUE candidate for <").append(info.getTagOrClassName()).append('>');
                if (info.getText() != null && !info.getText().isEmpty()) {
                    sb.append(" text=\"").append(info.getText()).append('"');
                }
                sb.append('\n');
                for (MobileLocatorCandidate candidate : info.getCandidates()) {
                    sb.append("    //   ").append(candidate.toReportLine()).append('\n');
                }
                sb.append('\n');
                continue;
            }
            sb.append("    @CacheLookup\n");
            sb.append("    ").append(toFindByAnnotation(info.getPlatform(), best)).append('\n');
            String baseName = JavaIdentifier.toFieldName(info.getSuggestedFieldName());
            int occurrence = fieldCounts.getOrDefault(baseName, 0) + 1;
            fieldCounts.put(baseName, occurrence);
            String fieldName = occurrence == 1 ? baseName : baseName + occurrence;
            sb.append("    public WebElement ").append(fieldName).append(";\n\n");
        }

        if (snapshot.hasWebViewContent()) {
            sb.append("    // WebView content detected on this screen -- see the crawler report and use\n");
            sb.append("    // com.test.automation.sdk.tools.pageobject.PageObjectGenerator.generateFromElements()\n");
            sb.append("    // to emit fields for it separately.\n\n");
        }

        sb.append("}\n");
        if (unresolvedCount > 0) {
            log.info("{} element(s) had no UNIQUE candidate and were emitted as comments only", unresolvedCount);
        }
        return sb.toString();
    }

    private static String toFindByAnnotation(String platform, MobileLocatorCandidate candidate) {
        boolean isIos = platform != null && platform.toLowerCase().contains("ios");
        String value = escape(candidate.getValue());
        if (isIos) {
            switch (candidate.getStrategy()) {
                case ACCESSIBILITY_ID:
                    return "@iOSXCUITFindBy(accessibility = \"" + value + "\")";
                case PREDICATE_STRING:
                    return "@iOSXCUITFindBy(iOSNsPredicate = \"" + value + "\")";
                case CLASS_CHAIN:
                    return "@iOSXCUITFindBy(iOSClassChain = \"" + value + "\")";
                default:
                    return "@iOSXCUITFindBy(xpath = \"" + value + "\")";
            }
        }
        switch (candidate.getStrategy()) {
            case RESOURCE_ID:
                return "@AndroidFindBy(id = \"" + value + "\")";
            case ACCESSIBILITY_ID:
                return "@AndroidFindBy(accessibility = \"" + value + "\")";
            case UIAUTOMATOR:
                return "@AndroidFindBy(uiAutomator = \"" + value + "\")";
            default:
                return "@AndroidFindBy(xpath = \"" + value + "\")";
        }
    }

    private static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    /** Renders and writes the page object to {@link #resolveOutputDir()}, returning the file path written. */
    public static String writeToFile(String className, MobileScreenSnapshot snapshot) {
        String source = generate(className, snapshot);
        String dir = resolveOutputDir();
        File dirFile = new File(dir);
        if (!dirFile.exists() && !dirFile.mkdirs()) {
            log.warn("Could not create mobile page object output directory: {}", dir);
        }
        File outFile = new File(dirFile, className + ".java");
        if (outFile.exists()) {
            outFile = new File(dirFile, className + "_Crawled.java");
            log.warn("{} already exists -- writing to {} instead so the hand-crafted file is not overwritten",
                    className + ".java", outFile.getName());
        }
        try (Writer writer = new FileWriter(outFile)) {
            writer.write(source);
        } catch (IOException e) {
            log.error("Failed to write mobile page object to {}", outFile.getAbsolutePath(), e);
        }
        return outFile.getPath();
    }
}
